sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tJCiTbhRiZHAN6umwga
    access-key-secret: 3YA26Y4QAWuHtjpM6ugRUT7BVShRkF
    bucket-name: sky-take-out-gj

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10